### ISSUE TITLE
Add Dependabot configuration

### ISSUE THREAD

**Issue by afuetterer** [PyPSA/powerplantmatching#172]
Hi,

to receive automatic updates for GitHub actions, like done in #171, I suggest adding a Dependabot configuration.

Suggested:
- monthly or quarterly schedule
- one PR for all GitHub actions updated

What do you think? Should I submit a PR?

Ref: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

**Comment by lkstrp** [comment]
Yes, that would be great! We use pre-commit to update those. I think Dependabot was going to support bumping pre-commits as well, but not sure what the status is. Would be great to have a tool which handles all the auto-updating, but since Actions are left out right now, feel free to submit a PR in any case. Thank you!

**Comment by afuetterer** [comment]
Alright.

Dependabot can update a lot of things, but sadly not the pre-commit config. Will submit a PR then.

**Comment by lkstrp** [comment]
Maybe some day: https://github.com/dependabot/dependabot-core/issues/1524
